services:
  mongodb:
    image: mongo
    ports:
      - 37017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./docker-data/mongodb:/data
